// flow-typed signature: 95004697c40859c3cd9f9dc614cf91aa
// flow-typed version: <<STUB>>/figlet_v^1.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'figlet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'figlet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'figlet/examples/front-end/jquery-1.7.2.min' {
  declare module.exports: any;
}

declare module 'figlet/examples/node/app' {
  declare module.exports: any;
}

declare module 'figlet/examples/node/appSync' {
  declare module.exports: any;
}

declare module 'figlet/Gruntfile' {
  declare module.exports: any;
}

declare module 'figlet/lib/figlet' {
  declare module.exports: any;
}

declare module 'figlet/lib/node-figlet' {
  declare module.exports: any;
}

declare module 'figlet/test/figlet_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'figlet/examples/front-end/jquery-1.7.2.min.js' {
  declare module.exports: $Exports<'figlet/examples/front-end/jquery-1.7.2.min'>;
}
declare module 'figlet/examples/node/app.js' {
  declare module.exports: $Exports<'figlet/examples/node/app'>;
}
declare module 'figlet/examples/node/appSync.js' {
  declare module.exports: $Exports<'figlet/examples/node/appSync'>;
}
declare module 'figlet/Gruntfile.js' {
  declare module.exports: $Exports<'figlet/Gruntfile'>;
}
declare module 'figlet/lib/figlet.js' {
  declare module.exports: $Exports<'figlet/lib/figlet'>;
}
declare module 'figlet/lib/node-figlet.js' {
  declare module.exports: $Exports<'figlet/lib/node-figlet'>;
}
declare module 'figlet/test/figlet_test.js' {
  declare module.exports: $Exports<'figlet/test/figlet_test'>;
}
