// flow-typed signature: d8a71829bdd7c46309307e9e5bcb654b
// flow-typed version: <<STUB>>/seneca_v^3.7.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seneca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seneca' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seneca/lib/actions' {
  declare module.exports: any;
}

declare module 'seneca/lib/api' {
  declare module.exports: any;
}

declare module 'seneca/lib/common' {
  declare module.exports: any;
}

declare module 'seneca/lib/errors' {
  declare module.exports: any;
}

declare module 'seneca/lib/inward' {
  declare module.exports: any;
}

declare module 'seneca/lib/legacy' {
  declare module.exports: any;
}

declare module 'seneca/lib/logging' {
  declare module.exports: any;
}

declare module 'seneca/lib/optioner' {
  declare module.exports: any;
}

declare module 'seneca/lib/outward' {
  declare module.exports: any;
}

declare module 'seneca/lib/plugins' {
  declare module.exports: any;
}

declare module 'seneca/lib/print' {
  declare module.exports: any;
}

declare module 'seneca/lib/transport' {
  declare module.exports: any;
}

declare module 'seneca/seneca' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seneca/lib/actions.js' {
  declare module.exports: $Exports<'seneca/lib/actions'>;
}
declare module 'seneca/lib/api.js' {
  declare module.exports: $Exports<'seneca/lib/api'>;
}
declare module 'seneca/lib/common.js' {
  declare module.exports: $Exports<'seneca/lib/common'>;
}
declare module 'seneca/lib/errors.js' {
  declare module.exports: $Exports<'seneca/lib/errors'>;
}
declare module 'seneca/lib/inward.js' {
  declare module.exports: $Exports<'seneca/lib/inward'>;
}
declare module 'seneca/lib/legacy.js' {
  declare module.exports: $Exports<'seneca/lib/legacy'>;
}
declare module 'seneca/lib/logging.js' {
  declare module.exports: $Exports<'seneca/lib/logging'>;
}
declare module 'seneca/lib/optioner.js' {
  declare module.exports: $Exports<'seneca/lib/optioner'>;
}
declare module 'seneca/lib/outward.js' {
  declare module.exports: $Exports<'seneca/lib/outward'>;
}
declare module 'seneca/lib/plugins.js' {
  declare module.exports: $Exports<'seneca/lib/plugins'>;
}
declare module 'seneca/lib/print.js' {
  declare module.exports: $Exports<'seneca/lib/print'>;
}
declare module 'seneca/lib/transport.js' {
  declare module.exports: $Exports<'seneca/lib/transport'>;
}
declare module 'seneca/seneca.js' {
  declare module.exports: $Exports<'seneca/seneca'>;
}
